from typing import Any, Text, Dict, List
from rasa_sdk import Action, Tracker
from rasa_sdk.executor import CollectingDispatcher
import difflib
import re

class ActionSpellCheck(Action):
    """Action pour corriger les fautes d'orthographe"""
    
    def name(self) -> Text:
        return "action_spell_check"
    
    def __init__(self):
        # Dictionnaire des corrections communes
        self.corrections = {
            # Fautes communes en français
            "rcp": "cpr",
            "defibrillateur": "defibrillator", 
            "arret": "arrest",
            "cardiaque": "cardiac",
            "coeur": "heart",
            "secours": "emergency",
            "urgence": "emergency",
            "respiration": "breathing",
            "bouche": "mouth",
            "compression": "compressions",
            "massage": "compressions",
            "poitrine": "chest",
            "thorax": "chest",
            "inconscient": "unconscious",
            "evanouie": "unconscious",
            "pouls": "pulse",
            "symptomes": "symptoms",
            "signes": "signs",
            "etranglement": "choking",
            "etouffement": "choking",
            "saignement": "bleeding",
            "hemorragie": "bleeding",
            "fracture": "fracture",
            "cassure": "fracture",
            "brulure": "burn",
            "avc": "stroke",
            "crise": "seizure",
            "epilepsie": "epilepsy",
            "allergie": "allergic",
            "reaction": "reaction",
            "choc": "shock",
            "hypothermie": "hypothermia",
            "noyade": "drowning",
            "empoisonnement": "poisoning",
            "surdose": "overdose",
            "colonne": "spinal",
            "vertebrale": "spinal",
            "grossesse": "pregnancy",
            "accouchement": "childbirth",
            "premiers": "first",
            "aide": "aid",
            "bandage": "bandage",
            "garrot": "tourniquet",
            "immobiliser": "immobilize",
            "stabiliser": "stabilize",
            "position": "position",
            "laterale": "recovery",
            "securite": "safety",
            "triage": "triage",
            "temoin": "bystander",
            "scene": "scene",
            "conscience": "consciousness",
            "reactif": "responsive",
            "voies": "airway",
            "aeriennes": "airway",
            "circulation": "circulation",
            "vitaux": "vital",
            "services": "services",
            "ambulancier": "paramedic",
            "hopital": "hospital",
            "clinique": "clinic",
            "medecin": "doctor",
            "infirmiere": "nurse",
            "professionnel": "professional",
            "medical": "medical",
            "formation": "training",
            "certification": "certification",
            "cours": "course",
            "apprendre": "learn",
            "pratiquer": "practice",
            "procedure": "procedure",
            "technique": "technique",
            "methode": "method",
            "etapes": "steps",
            "instructions": "instructions",
            "guide": "guide",
            "aider": "help",
            "assister": "assist",
            "sauver": "save",
            "vie": "life",
            "victime": "victim",
            "patient": "patient",
            "personne": "person",
            "quelqu'un": "someone",
            "n'importe": "anybody",
            "tout": "everyone",
            "urgent": "urgent",
            "critique": "critical",
            "severe": "severe",
            "serieux": "serious",
            "mineur": "minor",
            "majeur": "major",
            "immediat": "immediate",
            "rapidement": "quickly",
            "lentement": "slowly",
            "soigneusement": "carefully",
            "doucement": "gently",
            "fermement": "firmly",
            "fortement": "strongly",
            "pression": "pressure",
            "force": "force",
            "vitesse": "speed",
            "rythme": "rate",
            "cadence": "rhythm",
            "timing": "timing",
            "duree": "duration",
            "minutes": "minutes",
            "secondes": "seconds",
            "heures": "hours",
            "temperature": "temperature",
            "chaud": "hot",
            "froid": "cold",
            "tiede": "warm",
            "frais": "cool",
            "douleur": "pain",
            "mal": "hurt",
            "douloureux": "ache",
            "endolori": "sore",
            "engourdi": "numb",
            "picotement": "tingling",
            "gonflement": "swelling",
            "contusion": "bruising",
            "plaie": "wound",
            "coupure": "cut",
            "egratignure": "scrape",
            "ampoule": "blister",
            "eruption": "rash",
            "urticaire": "hives",
            "fievre": "fever",
            "nausee": "nausea",
            "vomissement": "vomiting",
            "vertige": "dizziness",
            "evanouissement": "fainting",
            "faiblesse": "weakness",
            "fatigue": "fatigue",
            "confusion": "confusion",
            "anxiete": "anxiety",
            "panique": "panic",
            "calme": "calm",
            "detendre": "relax",
            "respirer": "breathe",
            "inspirer": "inhale",
            "expirer": "exhale",
            "oxygene": "oxygen",
            "carbone": "carbon",
            "dioxyde": "dioxide",
            "sang": "blood",
            "rythme": "rate",
            "tension": "pressure",
            "irregulier": "irregular",
            "normal": "normal",
            "anormal": "abnormal",
            "rapide": "fast",
            "lent": "slow",
            "faible": "weak",
            "fort": "strong",
            "superficiel": "shallow",
            "profond": "deep",
            "laborieux": "labored",
            "difficulte": "difficulty",
            "obstruction": "obstruction",
            "blocage": "blockage",
            "degager": "clear",
            "ouvert": "open",
            "ferme": "closed",
            "gonfle": "swollen",
            "serre": "tight",
            "lache": "loose",
            "raide": "stiff",
            "flexible": "flexible",
            "mobile": "mobile",
            "immobile": "immobile",
            "stable": "stable",
            "instable": "unstable",
            "conscient": "conscious",
            "alerte": "alert",
            "somnolent": "drowsy",
            "lethargique": "lethargic",
            "comateux": "comatose",
            
            # Fautes communes en anglais
            "cpr": "cpr",
            "cardio": "cardiac",
            "pulmonary": "pulmonary",
            "resusitation": "resuscitation",
            "resucitation": "resuscitation",
            "resussitation": "resuscitation",
            "defibrilator": "defibrillator",
            "defibrillater": "defibrillator",
            "defibrilater": "defibrillator",
            "aed": "aed",
            "automated": "automated",
            "external": "external",
            "emergancy": "emergency",
            "emergeny": "emergency",
            "ambulence": "ambulance",
            "ambulanse": "ambulance",
            "brething": "breathing",
            "breathng": "breathing",
            "breathig": "breathing",
            "chest": "chest",
            "compressions": "compressions",
            "compresions": "compressions",
            "compressions": "compressions",
            "mouth": "mouth",
            "rescue": "rescue",
            "breaths": "breaths",
            "breathes": "breaths",
            "unconscious": "unconscious",
            "unconcious": "unconscious",
            "unconcsious": "unconscious",
            "pulse": "pulse",
            "puls": "pulse",
            "symptoms": "symptoms",
            "symtoms": "symptoms",
            "symptomes": "symptoms",
            "choking": "choking",
            "chocking": "choking",
            "chokeing": "choking",
            "heimlich": "heimlich",
            "heimlick": "heimlich",
            "heimlech": "heimlich",
            "maneuver": "maneuver",
            "manuever": "maneuver",
            "manoeuver": "maneuver",
            "bleeding": "bleeding",
            "bleding": "bleeding",
            "bledding": "bleeding",
            "fracture": "fracture",
            "fractur": "fracture",
            "fractuer": "fracture",
            "burn": "burn",
            "brun": "burn",
            "stroke": "stroke",
            "strok": "stroke",
            "seizure": "seizure",
            "siezure": "seizure",
            "seisure": "seizure",
            "epilepsy": "epilepsy",
            "epilepsey": "epilepsy",
            "epilepsi": "epilepsy",
            "allergic": "allergic",
            "alergic": "allergic",
            "allergik": "allergic",
            "reaction": "reaction",
            "reation": "reaction",
            "reacton": "reaction",
            "anaphylaxis": "anaphylaxis",
            "anaphilaxis": "anaphylaxis",
            "anafylaxis": "anaphylaxis",
            "epipen": "epipen",
            "epi-pen": "epipen",
            "epepen": "epipen",
            "epinephrine": "epinephrine",
            "epinefrine": "epinephrine",
            "epinephrin": "epinephrine",
            "hypothermia": "hypothermia",
            "hipothermia": "hypothermia",
            "hypothermea": "hypothermia",
            "hyperthermia": "hyperthermia",
            "hiperthermia": "hyperthermia",
            "hyperthermea": "hyperthermia",
            "drowning": "drowning",
            "drowing": "drowning",
            "drowning": "drowning",
            "poisoning": "poisoning",
            "poisonning": "poisoning",
            "poisening": "poisoning",
            "overdose": "overdose",
            "over-dose": "overdose",
            "overdos": "overdose",
            "spinal": "spinal",
            "spinel": "spinal",
            "spinall": "spinal",
            "injury": "injury",
            "injurie": "injury",
            "injuri": "injury",
            "pregnancy": "pregnancy",
            "pregnency": "pregnancy",
            "pregancy": "pregnancy",
            "childbirth": "childbirth",
            "child-birth": "childbirth",
            "childbrith": "childbirth",
            "shock": "shock",
            "shok": "shock",
            "schock": "shock",
            "medical": "medical",
            "medial": "medical",
            "medicall": "medical",
            "first": "first",
            "frist": "first",
            "fisrt": "first",
            "aid": "aid",
            "aide": "aid",
            "ade": "aid",
            "bandage": "bandage",
            "bandege": "bandage",
            "bandaje": "bandage",
            "tourniquet": "tourniquet",
            "tornique": "tourniquet",
            "tourniket": "tourniquet",
            "immobilize": "immobilize",
            "immobilise": "immobilize",
            "imobilize": "immobilize",
            "stabilize": "stabilize",
            "stabilise": "stabilize",
            "stablize": "stabilize",
            "recovery": "recovery",
            "recoveri": "recovery",
            "recuvery": "recovery",
            "position": "position",
            "postion": "position",
            "positon": "position",
            "triage": "triage",
            "triaje": "triage",
            "triag": "triage",
            "bystander": "bystander",
            "by-stander": "bystander",
            "bistander": "bystander",
            "scene": "scene",
            "scen": "scene",
            "sene": "scene",
            "safety": "safety",
            "safty": "safety",
            "saftey": "safety",
            "consciousness": "consciousness",
            "consciousnes": "consciousness",
            "conciousness": "consciousness",
            "responsive": "responsive",
            "responsiv": "responsive",
            "responive": "responsive",
            "airway": "airway",
            "air-way": "airway",
            "airwey": "airway",
            "circulation": "circulation",
            "circulaton": "circulation",
            "cirulation": "circulation",
            "vital": "vital",
            "vitall": "vital",
            "vitel": "vital",
            "signs": "signs",
            "sings": "signs",
            "signes": "signs",
            "services": "services",
            "servises": "services",
            "serveces": "services",
            "paramedic": "paramedic",
            "para-medic": "paramedic",
            "paramedik": "paramedic",
            "hospital": "hospital",
            "hospitall": "hospital",
            "hospitel": "hospital",
            "clinic": "clinic",
            "clinik": "clinic",
            "klinic": "clinic",
            "doctor": "doctor",
            "docter": "doctor",
            "dokter": "doctor",
            "nurse": "nurse",
            "nurs": "nurse",
            "nurce": "nurse",
            "professional": "professional",
            "profesional": "professional",
            "professionall": "professional",
            "training": "training",
            "trainning": "training",
            "traning": "training",
            "certification": "certification",
            "certifikation": "certification",
            "sertification": "certification",
            "course": "course",
            "cours": "course",
            "corse": "course",
            "learn": "learn",
            "lern": "learn",
            "leran": "learn",
            "practice": "practice",
            "practise": "practice",
            "practis": "practice",
            "procedure": "procedure",
            "procedur": "procedure",
            "prosedure": "procedure",
            "technique": "technique",
            "technik": "technique",
            "tecnique": "technique",
            "method": "method",
            "metod": "method",
            "methode": "method",
            "steps": "steps",
            "step": "steps",
            "stpes": "steps",
            "instructions": "instructions",
            "instruction": "instructions",
            "instrutions": "instructions",
            "guide": "guide",
            "guid": "guide",
            "gide": "guide",
            "help": "help",
            "halp": "help",
            "hepl": "help",
            "assist": "assist",
            "asist": "assist",
            "assit": "assist",
            "save": "save",
            "sav": "save",
            "safve": "save",
            "life": "life",
            "lif": "life",
            "live": "life",
            "victim": "victim",
            "viktim": "victim",
            "victom": "victim",
            "patient": "patient",
            "pacient": "patient",
            "patiant": "patient",
            "person": "person",
            "persn": "person",
            "persen": "person",
            "someone": "someone",
            "som1": "someone",
            "sumone": "someone",
            "anybody": "anybody",
            "any1": "anybody",
            "anybdy": "anybody",
            "everyone": "everyone",
            "every1": "everyone",
            "evryone": "everyone",
            "urgent": "urgent",
            "urgnt": "urgent",
            "urgant": "urgent",
            "critical": "critical",
            "critial": "critical",
            "critica": "critical",
            "severe": "severe",
            "sever": "severe",
            "sevear": "severe",
            "serious": "serious",
            "serius": "serious",
            "seriuos": "serious",
            "minor": "minor",
            "miner": "minor",
            "minr": "minor",
            "major": "major",
            "majer": "major",
            "majr": "major",
            "immediate": "immediate",
            "imediate": "immediate",
            "imidiate": "immediate",
            "quickly": "quickly",
            "quikly": "quickly",
            "quickli": "quickly",
            "slowly": "slowly",
            "slowli": "slowly",
            "sloly": "slowly",
            "carefully": "carefully",
            "carefuly": "carefully",
            "carfully": "carefully",
            "gently": "gently",
            "gentli": "gently",
            "gentely": "gently",
            "firmly": "firmly",
            "firmli": "firmly",
            "fermly": "firmly",
            "strongly": "strongly",
            "strongli": "strongly",
            "strongely": "strongly",
            "pressure": "pressure",
            "presure": "pressure",
            "pressur": "pressure",
            "force": "force",
            "forc": "force",
            "forse": "force",
            "speed": "speed",
            "sped": "speed",
            "spead": "speed",
            "rate": "rate",
            "rat": "rate",
            "reat": "rate",
            "rhythm": "rhythm",
            "rythm": "rhythm",
            "rhytm": "rhythm",
            "timing": "timing",
            "timming": "timing",
            "tming": "timing",
            "duration": "duration",
            "duraton": "duration",
            "duraction": "duration",
            "minutes": "minutes",
            "minuts": "minutes",
            "minites": "minutes",
            "seconds": "seconds",
            "secnds": "seconds",
            "secons": "seconds",
            "hours": "hours",
            "hors": "hours",
            "hrs": "hours",
            "temperature": "temperature",
            "temperatur": "temperature",
            "temprature": "temperature",
            "hot": "hot",
            "hott": "hot",
            "hoat": "hot",
            "cold": "cold",
            "col": "cold",
            "kold": "cold",
            "warm": "warm",
            "worm": "warm",
            "wrm": "warm",
            "cool": "cool",
            "kool": "cool",
            "col": "cool",
            "pain": "pain",
            "pan": "pain",
            "pian": "pain",
            "hurt": "hurt",
            "hrt": "hurt",
            "hert": "hurt",
            "ache": "ache",
            "ach": "ache",
            "ahe": "ache",
            "sore": "sore",
            "sor": "sore",
            "soar": "sore",
            "numb": "numb",
            "num": "numb",
            "nmb": "numb",
            "tingling": "tingling",
            "tinglng": "tingling",
            "tingeling": "tingling",
            "swelling": "swelling",
            "sweling": "swelling",
            "swelng": "swelling",
            "bruising": "bruising",
            "brusing": "bruising",
            "bruzing": "bruising",
            "wound": "wound",
            "wond": "wound",
            "woond": "wound",
            "cut": "cut",
            "kt": "cut",
            "cutt": "cut",
            "scrape": "scrape",
            "scrap": "scrape",
            "skrape": "scrape",
            "blister": "blister",
            "blster": "blister",
            "blistor": "blister",
            "rash": "rash",
            "resh": "rash",
            "rsh": "rash",
            "hives": "hives",
            "hivs": "hives",
            "haves": "hives",
            "fever": "fever",
            "fver": "fever",
            "fevr": "fever",
            "nausea": "nausea",
            "nausae": "nausea",
            "nausia": "nausea",
            "vomiting": "vomiting",
            "vomting": "vomiting",
            "vomitting": "vomiting",
            "dizziness": "dizziness",
            "diziness": "dizziness",
            "dizzyness": "dizziness",
            "fainting": "fainting",
            "fanting": "fainting",
            "faintng": "fainting",
            "weakness": "weakness",
            "weaknes": "weakness",
            "weaknss": "weakness",
            "fatigue": "fatigue",
            "fatig": "fatigue",
            "fatigu": "fatigue",
            "confusion": "confusion",
            "confusn": "confusion",
            "confusin": "confusion",
            "anxiety": "anxiety",
            "anxiet": "anxiety",
            "anxity": "anxiety",
            "panic": "panic",
            "panik": "panic",
            "pnic": "panic",
            "calm": "calm",
            "kalm": "calm",
            "clam": "calm",
            "relax": "relax",
            "relaks": "relax",
            "rilax": "relax",
            "breathe": "breathe",
            "breath": "breathe",
            "breth": "breathe",
            "inhale": "inhale",
            "inhal": "inhale",
            "inhaile": "inhale",
            "exhale": "exhale",
            "exhal": "exhale",
            "exhail": "exhale",
            "oxygen": "oxygen",
            "oxigen": "oxygen",
            "oxygn": "oxygen",
            "carbon": "carbon",
            "carbn": "carbon",
            "karbon": "carbon",
            "dioxide": "dioxide",
            "dioxid": "dioxide",
            "dioxyde": "dioxide",
            "blood": "blood",
            "blod": "blood",
            "blud": "blood",
            "irregular": "irregular",
            "iregular": "irregular",
            "irregulr": "irregular",
            "normal": "normal",
            "norml": "normal",
            "normall": "normal",
            "abnormal": "abnormal",
            "abnorml": "abnormal",
            "abnormall": "abnormal",
            "fast": "fast",
            "fst": "fast",
            "fase": "fast",
            "slow": "slow",
            "slo": "slow",
            "slw": "slow",
            "weak": "weak",
            "wek": "weak",
            "waek": "weak",
            "strong": "strong",
            "strng": "strong",
            "stong": "strong",
            "shallow": "shallow",
            "shalow": "shallow",
            "shalw": "shallow",
            "deep": "deep",
            "dep": "deep",
            "deap": "deep",
            "labored": "labored",
            "labord": "labored",
            "laborred": "labored",
            "difficulty": "difficulty",
            "dificulty": "difficulty",
            "dificulti": "difficulty",
            "obstruction": "obstruction",
            "obstrction": "obstruction",
            "obstruktion": "obstruction",
            "blockage": "blockage",
            "blokage": "blockage",
            "blockaj": "blockage",
            "clear": "clear",
            "cler": "clear",
            "klear": "clear",
            "open": "open",
            "opn": "open",
            "opan": "open",
            "closed": "closed",
            "closd": "closed",
            "klosed": "closed",
            "swollen": "swollen",
            "swoln": "swollen",
            "swolen": "swollen",
            "tight": "tight",
            "tght": "tight",
            "tigt": "tight",
            "loose": "loose",
            "loos": "loose",
            "luse": "loose",
            "stiff": "stiff",
            "stif": "stiff",
            "stff": "stiff",
            "flexible": "flexible",
            "flexibl": "flexible",
            "flexable": "flexible",
            "mobile": "mobile",
            "mobil": "mobile",
            "moble": "mobile",
            "immobile": "immobile",
            "imobile": "immobile",
            "imobil": "immobile",
            "stable": "stable",
            "stabl": "stable",
            "stabel": "stable",
            "unstable": "unstable",
            "unstabl": "unstable",
            "unstabel": "unstable",
            "conscious": "conscious",
            "consciou": "conscious",
            "concious": "conscious",
            "alert": "alert",
            "alrt": "alert",
            "alart": "alert",
            "drowsy": "drowsy",
            "drowsi": "drowsy",
            "drousy": "drowsy",
            "lethargic": "lethargic",
            "lethargik": "lethargic",
            "letargic": "lethargic",
            "comatose": "comatose",
            "comatos": "comatose",
            "komatose": "comatose"
        }
        
        # Mots médicaux importants pour la détection
        self.medical_terms = [
            "cpr", "cardiac", "arrest", "heart", "attack", "defibrillator", "aed",
            "emergency", "breathing", "chest", "compressions", "mouth", "rescue",
            "unconscious", "pulse", "symptoms", "choking", "bleeding", "fracture",
            "burn", "stroke", "seizure", "allergic", "reaction", "shock", "first", "aid"
        ]
    
    def correct_spelling(self, text: str) -> str:
        """Corrige les fautes d'orthographe dans le texte"""
        words = text.lower().split()
        corrected_words = []
        
        for word in words:
            # Nettoie la ponctuation
            clean_word = re.sub(r'[^\w]', '', word)
            
            # Vérifie les corrections directes
            if clean_word in self.corrections:
                corrected_words.append(self.corrections[clean_word])
            else:
                # Utilise difflib pour trouver des mots similaires
                best_match = self.find_best_match(clean_word)
                corrected_words.append(best_match if best_match else clean_word)
        
        return ' '.join(corrected_words)
    
    def find_best_match(self, word: str) -> str:
        """Trouve le meilleur match pour un mot mal orthographié"""
        if len(word) < 3:
            return word
            
        # Cherche dans les termes médicaux
        matches = difflib.get_close_matches(
            word, 
            self.medical_terms + list(self.corrections.values()), 
            n=1, 
            cutoff=0.6
        )
        
        return matches[0] if matches else word
    
    def run(self, dispatcher: CollectingDispatcher,
            tracker: Tracker,
            domain: Dict[Text, Any]) -> List[Dict[Text, Any]]:
        
        user_message = tracker.latest_message.get('text', '')
        corrected_message = self.correct_spelling(user_message)
        
        # Si le message a été corrigé, informe l'utilisateur
        if corrected_message.lower() != user_message.lower():
            dispatcher.utter_message(
                text=f"Je pense que vous vouliez dire: '{corrected_message}'. Laissez-moi vous aider avec ça."
            )
        
        return []


class ActionSuggestCorrection(Action):
    """Action pour suggérer des corrections quand la confiance est faible"""
    
    def name(self) -> Text:
        return "action_suggest_correction"
    
    def run(self, dispatcher: CollectingDispatcher,
            tracker: Tracker,
            domain: Dict[Text, Any]) -> List[Dict[Text, Any]]:
        
        # Suggestions basées sur des mots-clés partiels
        user_message = tracker.latest_message.get('text', '').lower()
        
        suggestions = []
        
        if any(word in user_message for word in ['cpr', 'rcp', 'cardio', 'heart', 'coeur']):
            suggestions.extend([
                "Comment faire la RCP ?",
                "Qu'est-ce que la RCP ?",
                "Étapes de la RCP"
            ])
        
        if any(word in user_message for word in ['symptom', 'sign', 'detect']):
            suggestions.extend([
                "Symptômes d'arrêt cardiaque",
                "Signes d'urgence médicale",
                "Comment reconnaître un problème"
            ])
        
        if any(word in user_message for word in ['emergency', 'urgence', 'help', 'aide']):
            suggestions.extend([
                "Numéros d'urgence",
                "Que faire en cas d'urgence",
                "Premiers secours"
            ])
        
        if any(word in user_message for word in ['chok', 'etou', 'breath']):
            suggestions.extend([
                "Que faire en cas d'étouffement",
                "Manœuvre de Heimlich",
                "Problèmes respiratoires"
            ])
        
        if suggestions:
            buttons = [{"title": suggestion, "payload": f"/{suggestion.lower().replace(' ', '_').replace('?', '').replace('é', 'e').replace('è', 'e').replace('à', 'a')}"} 
                      for suggestion in suggestions[:3]]
            
            dispatcher.utter_message(
                text="Je n'ai pas bien compris votre question. Vouliez-vous demander :",
                buttons=buttons
            )
        else:
            dispatcher.utter_message(
                text="Désolé, je n'ai pas compris votre question. Pouvez-vous la reformuler ? Je peux vous aider avec la RCP, les premiers secours, les urgences médicales, etc."
            )
        
        return []