services:
  rasa:
    container_name: crp_chatbot
    image: rasa/rasa:3.6.20-full
    volumes:
      - ./:/app
    command:
      - run
      - --enable-api
      - --cors
      - "*"
    ports:
      - "5006:5005"
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    restart: always
    shm_size: 128mb
    env_file:
      - ./docker/postgres/.env
    volumes:
      - ./docker/postgres:/docker-entrypoint-initdb.d

  analytics:
    container_name: analytics
    build: ./analytics
    env_file:
      - ./docker/analytics/.env
      - ./docker/postgres/.env
    ports:
      - "5005:3000"
    depends_on:
      - rasa
      - db