version: "3.9"

services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    env_file:
      - ./docker/postgres/.env
    volumes:
      - ./docker/postgres:/docker-entrypoint-initdb.d
    ports:
      - "5435:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
